version: '3.9'
services:
  app:
    build:
      dockerfile: Dockerfile
    ports:
      - "8801:8801"
    depends_on:
      - "db"
    networks:
      - emoneynetwork
    restart: on-failure
    environment:
      - WAIT_HOSTS=e_money_db:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=30
  db:
    image: mysql:5.7
    container_name: e_money_db
    restart: unless-stopped
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - emoneynetwork

networks:
   emoneynetwork:
      driver: bridge